# -*- coding: utf-8 -*-
import logging
import re

from lxml import etree

from odoo import api, models

_logger = logging.getLogger(__name__)


class IrUiView(models.Model):
    _inherit = "ir.ui.view"

    @api.model
    def l10n_mx_force_retry_install_views(self):
        """Insert our button next to the *actual* Retry button used by MX CFDI.

        ``l10n_mx_edi`` is Enterprise and its internal view XML IDs/structure can
        change between revisions.  Instead of depending on one private XML ID,
        locate the object Retry buttons from the installed views and create
        small inherited views next to them.  This is executed on install and on
        every module upgrade.
        """
        View = self.sudo().with_context(lang=None)

        # Remove views generated by an older execution so the upgrade is clean.
        old_generated = View.search([
            ("name", "like", "l10n.mx.force.retry.generated.%"),
        ])
        if old_generated:
            old_generated.unlink()

        candidates = View.search([
            ("active", "=", True),
            ("type", "in", ("form", "list")),
            ("model", "in", ("account.move", "l10n_mx_edi.document")),
        ])

        created = 0
        seen = set()
        for parent in candidates:
            arch = parent.arch_db or ""
            lower_arch = arch.lower()
            identity = f"{parent.name or ''} {parent.key or ''} {parent.model or ''} {lower_arch}".lower()
            if not any(marker in identity for marker in ("l10n_mx", "cfdi", "account_edi", "edi_document")):
                continue
            if "<button" not in lower_arch:
                continue

            try:
                root = etree.fromstring(arch.encode())
            except Exception:
                continue

            for button in root.xpath(".//button[@type='object']"):
                method = (button.get("name") or "").strip()
                label = (button.get("string") or "").strip().lower()
                if not method:
                    continue
                retry_like = (
                    "retry" in method.lower()
                    or "retry" in label
                    or "volver a intentar" in label
                    or "reintentar" in label
                )
                if not retry_like:
                    continue
                if method == "action_force_retry_edi_payment_decimals":
                    continue
                marker = (parent.id, method)
                if marker in seen:
                    continue
                seen.add(marker)

                # XPath literal. Method names are normal identifiers, but escape
                # defensively in case Odoo changes the value.
                if "'" in method:
                    continue
                expr = f"//button[@name='{method}']"

                attrs = [
                    'name="action_force_retry_edi_payment_decimals"',
                    'type="object"',
                    'string="Forzar volver a intentar"',
                    'class="oe_link oe_inline"',
                    'confirm="Se hará un reintento normal y, si el PAC devuelve CRP20268 o CRPER654, se aplicará automáticamente la corrección correspondiente. ¿Deseas continuar?"',
                    f"context=\"{{'l10n_mx_force_retry_source_method': '{method}'}}\"",
                ]
                for attr_name in ("invisible", "column_invisible", "groups"):
                    value = button.get(attr_name)
                    if value:
                        value = value.replace("&", "&amp;").replace('"', "&quot;").replace("<", "&lt;").replace(">", "&gt;")
                        attrs.append(f'{attr_name}="{value}"')

                generated_arch = (
                    f'<xpath expr="{expr}" position="after">'
                    f'<button {" ".join(attrs)}/>'
                    f'</xpath>'
                )

                safe_method = re.sub(r"[^a-zA-Z0-9_.-]+", "_", method)[:60]
                name = f"l10n.mx.force.retry.generated.{parent.id}.{safe_method}"
                try:
                    with self.env.cr.savepoint():
                        View.create({
                            "name": name,
                            "type": parent.type,
                            "model": parent.model,
                            "inherit_id": parent.id,
                            "priority": 999,
                            "mode": "extension",
                            "arch_db": generated_arch,
                        })
                    created += 1
                except Exception:
                    _logger.exception(
                        "Could not add force retry button after %s in view %s (%s)",
                        method, parent.name, parent.id,
                    )
                    # Keep scanning: another candidate can be the MX CFDI row
                    # actually rendered in the invoice tab.

        _logger.info("MX force retry: generated %s retry-button view(s)", created)
        return True
